# -*- coding: utf-8 -*-
"""text to image

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d6sEWhD7WhCgbarceiLHdOUc6arFqBGB
"""

pip install --upgrade diffusers transformers -q

! pip install streamlit -q

!wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501

pip install --upgrade diffusers transformers -q

from pathlib import Path
import tqdm
import torch
import pandas as pd
import numpy as np
from diffusers import StableDiffusionPipeline
from transformers import pipeline, set_seed
import matplotlib.pyplot as plt
import cv2

class CFG:
  device="cuda"
  seed=42
  generator=torch.Generator(device).manual_seed(seed)
  image_gen_steps=35
  image_gen_model_id="stabilityai/stable-diffusion-2"
  image_gen_size=(400,400)
  image_gen_guidance_scale=9
  prompt_gen_model_id="gpt2"
  prompt_dataset_size=6
  prompt_max_length=12

from google.colab import userdata
userdata.get('key')

image_gen_model=StableDiffusionPipeline.from_pretrained(
    CFG.image_gen_model_id,torch_dtype = torch.float16,revision="fp16",use_auth_token=userdata.get('key'),guidance_scale=9).to(CFG.device)

def generate_image(prompt,model):
  image=model(prompt,num_inference_steps=CFG.image_gen_steps,generator=CFG.generator,guidance_scale=CFG.image_gen_guidance_scale).images[0]

  image=image.resize(CFG.image_gen_size)

  return image

prompt=str(input("Enter your prompt: "))
generate_image(prompt,image_gen_model)

